extends:
  - '@commitlint/config-conventional'

rules:
  # Enforce conventional commits
  type-enum:
    - 2
    - always
    -
      - feat     # A new feature
      - fix      # A bug fix
      - docs     # Documentation only changes
      - style    # Changes that do not affect the meaning of the code
      - refactor # A code change that neither fixes a bug nor adds a feature
      - perf     # A code change that improves performance
      - test     # Adding missing tests or correcting existing tests
      - build    # Changes that affect the build system or external dependencies
      - ci       # Changes to our CI configuration files and scripts
      - chore    # Other changes that don't modify src or test files
      - revert   # Reverts a previous commit
      - wip      # Work in progress

  # Require scope for feat and fix
  scope-enum:
    - 2
    - always
    -
      - parser
      - executor
      - output
      - types
      - cli
      - config
      - deps
      - test
      - docs
      - build
      - ci
      - "*"

  # Enforce subject is lowercase
  subject-case:
    - 2
    - always
    - lower-case

  # Enforce subject doesn't end with period
  subject-full-stop:
    - 2
    - never
    - "."

  # Enforce subject is not empty
  subject-empty:
    - 2
    - never

  # Enforce max line length
  header-max-length:
    - 2
    - always
    - 72

  # Enforce body line length
  body-max-line-length:
    - 2
    - always
    - 72

  # Enforce footer line length
  footer-max-line-length:
    - 2
    - always
    - 72

  # Require signed-off-by for contributions
  signed-off-by:
    - 0
    - always

# Example valid commits:
# feat(parser): add support for nested HCL blocks
# fix(executor): resolve timeout issue with large requests
# docs: update README with installation instructions
# refactor: simplify configuration merging logic
# test: add coverage for edge cases in converter
