run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - goconst
    - gocyclo
    - dupl
    - gochecknoinits
    - misspell
    - lll

linters-settings:
  govet:
    check-shadowing: true

  misspell:
    locale: US

  goconst:
    min-len: 3
    min-occurrences: 3

  gocyclo:
    min-complexity: 15

  lll:
    line-length: 120

  dupl:
    threshold: 100

  gochecknoinits:
    exclude-tests: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll

    # Exclude known linter issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    # Exclude shadow checking on err variables
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

    # Exclude magic number warnings for common values
    - text: "Magic number: [0-2]"
      linters:
        - goconst

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true