version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - goconst
    - gocyclo
    - dupl
    - misspell
    - lll

  settings:
    govet:
      enable:
        - shadow

    misspell:
      locale: US

    goconst:
      min-len: 3
      min-occurrences: 3

    gocyclo:
      min-complexity: 15

    lll:
      line-length: 120

    dupl:
      threshold: 100

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - lll

      - text: "weak cryptographic primitive"
        linters:
          - gosec

      - text: "shadow: declaration of \"err\""
        linters:
          - govet

      - text: "Magic number: [0-2]"
        linters:
          - goconst

output:
  formats:
    text:
      path: stdout
      colors: true
