project_name: rpc-cli

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: rpc-cli
    main: ./cmd/rpc-cli
    binary: rpc-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: rpc-cli
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - CHANGELOG.md
      - ARCHITECTURE.md
      - requests.hcl

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Enhancements"
      regexp: "^.*enhance[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: gelleson
    name: jsonrpc
  draft: false
  prerelease: auto
  mode: append
  name_template: "v{{.Version}}"
  header: |
    ## rpc-cli {{.Version}}

    Execute JSON-RPC requests defined in HCL configuration files.

    ### Installation

    #### Binary Download
    Download the appropriate binary for your platform from the assets below.

    #### Install Script
    ```bash
    curl -sSL https://raw.githubusercontent.com/gelleson/jsonrpc/main/install.sh | bash
    ```

    #### Go Install
    ```bash
    go install github.com/gelleson/jsonrpc/cmd/rpc-cli@{{.Version}}
    ```

    ### What's Changed

  footer: |
    **Full Changelog**: https://github.com/gelleson/jsonrpc/compare/{{ .PreviousTag }}...{{ .Tag }}

announce:
  skip: true
